### ISSUE TITLE
EASE2_M9KM grid issue

### ISSUE THREAD

**Issue by aschae11** [TUW-GEO/ease-grid#3]
When I use the EASE2_grid call with 9000 meters as the input, we receive a grid of 1628x3858 instead of the 1624x3856 that it should be.  Any thoughts on why this may be?

>>> from ease_grid import EASE2_grid
>>> egrid = EASE2_grid(36000)
>>> egrid.shape
(406, 964)
>>> egrid = EASE2_grid(9000)
>>> egrid.shape
(1628, 3858)
>>>

**Comment by cpaulik** [comment]
Yes this is confusing. NASA does not use a `map_scale` of `9000` for the `EASE2_M09KM` grid. The scale that they use is `9008.055210146`. So if you call 

```python
EASE2_grid(9008.055210146)
```
it should be correct.

You can find the scales that they use in the `ease2_grid_info.pro` file as described [here](https://github.com/TUW-GEO/ease_grid#supported-ease-grids)

**Comment by aschae11** [comment]
Per you suggestion, I tried using NASA's map scalars and I still do not receive a correctly shaped array.
``` python
>>> grid = EASE2_grid(9008.055210146)
>>> grid.shape
(1628, 3854)
```

After further investigation, none of the global map scalars (36, 9, 3, 1 km) in `ease2_grid_info.pro` file yield the correct grid for me. The only one that comes close is when I use the the even 36km.

``` python
>>> grid3 = EASE2_grid(3002.6850700487)
>>> grid3.shape
(4888, 11566)
>>> grid4 = EASE2_grid(1000.89502334956)
>>> grid4.shape
(14668, 34702)
>>> grid5 = EASE2_grid(36032.220840584)
>>> grid5.shape
(404, 962)
>>> grid6 = EASE2_grid(36000)
>>> grid6.shape
(406, 964)
```

Suggestions?

**Comment by cpaulik** [comment]
Seeing your post I remembered that I had similar problems when I wrote this package. Back then I wrote to NASA about it and they told me (if I remember correctly) that they do not use the EASE2 grid computation from scratch for each grid but they make sure that the grid size is a multiple of the base grid.

e.g. The 9km grid is based on the 36km grid. This is the reason why it has the size of 3856x1624 which is exactly 4 times the base grid size of 964x406.

So unfortunately this package does not do what you want at the moment. It basically only implements the EASE grid paper but not the special assumptions that NASA has made in their grid systems.

**Comment by aschae11** [comment]
Ah, ok. Thanks for clarifying.

**Comment by jonhealy1** [comment]
> When I use the EASE2_grid call with 9000 meters as the input, we receive a grid of 1628x3858 instead of the 1624x3856 that it should be. Any thoughts on why this may be?
> 
> > > > from ease_grid import EASE2_grid
> > > > egrid = EASE2_grid(36000)
> > > > egrid.shape
> > > > (406, 964)
> > > > egrid = EASE2_grid(9000)
> > > > egrid.shape
> > > > (1628, 3858)

A 9km grid should be something like 812*1928 I think. This would make 4 times as many grids. There would be twice as many grids on the x axis and twice as many on the y. There are 4 9km grids in a 36km grid.

**Comment by jonhealy1** [comment]
This is from the ease grid dggs paper 
<img width="683" alt="Screen Shot 2022-06-08 at 1 53 24 AM" src="https://user-images.githubusercontent.com/19381236/172599435-cd5ba4dd-6852-4a55-9d0c-a77396ceb51a.png">
